apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_ENDPOINT: "mysql-svc"   # ⬅️ Magia: Kubernetes resuelve este nombre internamente
  DB_USERNAME: "root"        # ⬅️ El usuario administrador de MySQL
  DB_PASSWORD: "admin123"    # ⬅️ La contraseña que pusimos en el paso 1
  DB_NAME: "innovatech_db"   # ⬅️ El nombre de la base de datos